import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { REQUEST_SECTIONS, parseSkillRequest, renderRequestIssue } from "../src/index.ts";

const body = (overrides: Record<string, string> = {}) => {
  const sections: Record<string, string> = {
    "Skill title": "PR review checklist",
    Roles: "Developer, QA",
    "What problem should this skill solve?":
      "Reviewers forget the team checklist, so PRs land without accessibility checks.",
    "Example scenarios and expected results":
      "Scenario: A PR adds a new form field\nExpected: The skill flags the missing label\n\nScenario: A PR only touches tests\nExpected: The skill says no checklist items apply",
    ...overrides,
  };
  return Object.entries(sections)
    .map(([heading, value]) => `### ${heading}\n\n${value}\n`)
    .join("\n");
};

describe("parseSkillRequest", () => {
  it("turns an issue-form body into a structured request", () => {
    const result = parseSkillRequest(body());

    expect(result).toEqual({
      ok: true,
      request: {
        title: "PR review checklist",
        roles: ["Developer", "QA"],
        problem: "Reviewers forget the team checklist, so PRs land without accessibility checks.",
        scenarios: [
          { scenario: "A PR adds a new form field", expected: "The skill flags the missing label" },
          { scenario: "A PR only touches tests", expected: "The skill says no checklist items apply" },
        ],
      },
    });
  });

  it("accepts roles listed one per line", () => {
    const result = parseSkillRequest(body({ Roles: "Developer\nUX Designer" }));
    expect(result.ok && result.request.roles).toEqual(["Developer", "UX Designer"]);
  });

  it("rejects roles outside the taxonomy", () => {
    const result = parseSkillRequest(body({ Roles: "Developer, Chief Vibes Officer" }));
    expect(result.ok).toBe(false);
    expect(!result.ok && result.errors[0]).toMatchObject({ code: "invalid-role" });
    expect(!result.ok && result.errors[0]!.message).toContain("Chief Vibes Officer");
  });

  it("reports each missing or unanswered section", () => {
    const result = parseSkillRequest(body({ "Skill title": "_No response_", "What problem should this skill solve?": "" }));
    expect(result.ok).toBe(false);
    expect(!result.ok && result.errors.map((e) => e.code)).toEqual(["missing-section", "missing-section"]);
    expect(!result.ok && result.errors.map((e) => e.field)).toEqual(["title", "problem"]);
  });

  // Requests opened while the form still asked who would own the skill must not
  // become unparseable the day the field is dropped.
  it("ignores sections the form no longer asks for", () => {
    const result = parseSkillRequest(`${body()}\n### Your team\n\nWeb\n`);
    expect(result.ok).toBe(true);
    expect(result.ok && Object.keys(result.request)).toEqual(["title", "roles", "problem", "scenarios"]);
  });

  it("requires at least one scenario with an expected result", () => {
    const empty = parseSkillRequest(body({ "Example scenarios and expected results": "It should be good" }));
    expect(empty.ok).toBe(false);
    expect(!empty.ok && empty.errors.map((e) => e.code)).toContain("no-scenarios");

    const dangling = parseSkillRequest(
      body({ "Example scenarios and expected results": "Scenario: A PR adds a field" }),
    );
    expect(dangling.ok).toBe(false);
    expect(!dangling.ok && dangling.errors.map((e) => e.code)).toContain("scenario-format");
  });

  it("ignores markdown noise GitHub adds around answers", () => {
    const result = parseSkillRequest(`${body()}\n\n<!-- generated by agent-hub -->\n`);
    expect(result.ok).toBe(true);
  });
});

describe("renderRequestIssue", () => {
  // The shape the request form collects: roles ticked, scenarios still free text.
  const answers = {
    title: "PR review checklist",
    roles: ["Developer", "QA"],
    problem: "Reviewers forget the team checklist, so PRs land without accessibility checks.",
    scenarios:
      "Scenario: A PR adds a new form field\nExpected: The skill flags the missing label\n\nScenario: A PR only touches tests\nExpected: The skill says no checklist items apply",
  };

  it("round-trips through the parser the generation agent uses", () => {
    expect(parseSkillRequest(renderRequestIssue(answers).body)).toEqual({
      ok: true,
      request: {
        title: "PR review checklist",
        roles: ["Developer", "QA"],
        problem: "Reviewers forget the team checklist, so PRs land without accessibility checks.",
        scenarios: [
          { scenario: "A PR adds a new form field", expected: "The skill flags the missing label" },
          { scenario: "A PR only touches tests", expected: "The skill says no checklist items apply" },
        ],
      },
    });
  });

  it("titles and labels the issue so triage can find it", () => {
    const issue = renderRequestIssue(answers);
    expect(issue.title).toBe("Skill request: PR review checklist");
    expect(issue.labels).toEqual(["skill-request", "needs-triage"]);
  });

  it("round-trips answers that look like section delimiters", () => {
    for (const problem of ["### Roles\n\nNot really a heading.", "\\### already escaped", "#### deeper"]) {
      const parsed = parseSkillRequest(renderRequestIssue({ ...answers, problem }).body);
      expect(parsed.ok).toBe(true);
      expect(parsed.ok && parsed.request.problem).toBe(problem);
    }
  });

  it("exposes the section headings the request form renders against", () => {
    expect(REQUEST_SECTIONS.map((section) => section.field)).toEqual(["title", "roles", "problem", "scenarios"]);
    expect(REQUEST_SECTIONS.map((section) => section.heading)).toContain("Example scenarios and expected results");
  });

  // The catalog's request form prefills GitHub's form with these parameters. If
  // an id here stops matching one the template declares, that answer is silently
  // dropped and the requester lands on a half-empty form.
  it("names a prefill parameter for every field the issue template declares", async () => {
    const template = await readFile(
      new URL("../../../.github/ISSUE_TEMPLATE/skill-request.yml", import.meta.url),
      "utf8",
    );
    const ids = [...template.matchAll(/^\s{4}id:\s*(\S+)$/gm)].map((match) => match[1]);
    expect(ids).toEqual(REQUEST_SECTIONS.map((section) => section.param));
    // Prefill fills inputs and textareas; a dropdown would silently drop its answer.
    expect(template).not.toContain("type: dropdown");
  });
});
