import { describe, expect, it } from "vitest";
import { parseSkillRequest } from "../src/index.ts";

const body = (overrides: Record<string, string> = {}) => {
  const sections: Record<string, string> = {
    "Skill title": "PR review checklist",
    Roles: "Developer, QA",
    "What problem should this skill solve?":
      "Reviewers forget the team checklist, so PRs land without accessibility checks.",
    "Example scenarios and expected results":
      "Scenario: A PR adds a new form field\nExpected: The skill flags the missing label\n\nScenario: A PR only touches tests\nExpected: The skill says no checklist items apply",
    "Your team": "Web",
    ...overrides,
  };
  return Object.entries(sections)
    .map(([heading, value]) => `### ${heading}\n\n${value}\n`)
    .join("\n");
};

describe("parseSkillRequest", () => {
  it("turns an issue-form body into a structured request", () => {
    const result = parseSkillRequest(body());

    expect(result).toEqual({
      ok: true,
      request: {
        title: "PR review checklist",
        roles: ["Developer", "QA"],
        problem: "Reviewers forget the team checklist, so PRs land without accessibility checks.",
        scenarios: [
          { scenario: "A PR adds a new form field", expected: "The skill flags the missing label" },
          { scenario: "A PR only touches tests", expected: "The skill says no checklist items apply" },
        ],
        team: "Web",
      },
    });
  });

  it("accepts roles listed one per line", () => {
    const result = parseSkillRequest(body({ Roles: "Developer\nUX Designer" }));
    expect(result.ok && result.request.roles).toEqual(["Developer", "UX Designer"]);
  });

  it("rejects roles outside the taxonomy", () => {
    const result = parseSkillRequest(body({ Roles: "Developer, Chief Vibes Officer" }));
    expect(result.ok).toBe(false);
    expect(!result.ok && result.errors[0]).toMatchObject({ code: "invalid-role" });
    expect(!result.ok && result.errors[0]!.message).toContain("Chief Vibes Officer");
  });

  it("reports each missing or unanswered section", () => {
    const result = parseSkillRequest(body({ "Your team": "_No response_", "What problem should this skill solve?": "" }));
    expect(result.ok).toBe(false);
    expect(!result.ok && result.errors.map((e) => e.code)).toEqual(["missing-section", "missing-section"]);
    expect(!result.ok && result.errors.map((e) => e.field)).toEqual(["problem", "team"]);
  });

  it("requires at least one scenario with an expected result", () => {
    const empty = parseSkillRequest(body({ "Example scenarios and expected results": "It should be good" }));
    expect(empty.ok).toBe(false);
    expect(!empty.ok && empty.errors.map((e) => e.code)).toContain("no-scenarios");

    const dangling = parseSkillRequest(
      body({ "Example scenarios and expected results": "Scenario: A PR adds a field" }),
    );
    expect(dangling.ok).toBe(false);
    expect(!dangling.ok && dangling.errors.map((e) => e.code)).toContain("scenario-format");
  });

  it("ignores markdown noise GitHub adds around answers", () => {
    const result = parseSkillRequest(`${body()}\n\n<!-- generated by agent-hub -->\n`);
    expect(result.ok).toBe(true);
  });
});
